name: Build & Test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: macos-15
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4
        timeout-minutes: 5
        with:
          fetch-depth: 0
      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.15+6'
      - name: Select XCode 16.3
        run: |
          sudo xcode-select -s /Applications/Xcode_16.3.app/Contents/Developer
          xcodebuild -version
      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/native
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Kotlin Native Cache
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Android Cache
        uses: actions/cache@v4
        with:
          path: ~/.android
          key: ${{ runner.os }}-android-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-android-
      - name: Build & Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build test detekt assembleXCFramework --parallel
      - name: Set RELEASE_VERSION variable
        run: |
          echo "RELEASE_VERSION=$(cat build/version.txt)" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports.zip
          path: build/reports
      - name: List files
        run: |
          ls -lah build/bin/*/releaseExecutable build/libs/  build/outputs/aar/ build/XCFrameworks/release/
      - name: Upload xmpcore.jar
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: xmpcore.jar
          path: build/libs/xmpcore-jvm-${{ env.RELEASE_VERSION }}.jar
      - name: Upload xmpcore.aar
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: xmpcore.aar
          path: build/outputs/aar/xmpcore-release.aar
      - name: Upload xmpcore.xcframework
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: xmpcore.xcframework
          path: build/XCFrameworks/release/xmpcore.xcframework
      - name: Upload xmpcore.exe
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: xmpcore.exe
          path: build/bin/win/releaseExecutable/xmpcore.exe
      - name: Upload xmpcore-macosX64.kexe
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: xmpcore-macosX64.kexe
          path: build/bin/macosX64/releaseExecutable/xmpcore.kexe
      - name: Upload xmpcore-macosArm64.kexe
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: xmpcore-macosArm64.kexe
          path: build/bin/macosArm64/releaseExecutable/xmpcore.kexe
      - name: Upload xmpcore-linuxArm64.kexe
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: xmpcore-linuxArm64.kexe
          path: build/bin/linuxArm64/releaseExecutable/xmpcore.kexe
      - name: Upload xmpcore-linuxX64.kexe
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: xmpcore-linuxX64.kexe
          path: build/bin/linuxX64/releaseExecutable/xmpcore.kexe
      - name: Publish to Maven Central
        if: startsWith(github.ref, 'refs/tags/') # Only for releases
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          SIGNING_ENABLED: true
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SINGING_SECRET_KEY_RING_FILE_CONTENTS }}
